{{ if .Values.advancedClusterManagement }}
---
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  disableHubSelfManagement: {{ .Values.advancedClusterManagement.disableHubSelfManagement | default false }}
{{- if .Values.advancedClusterManagement.enableRHEM }}
  overrides:
    components:
      - configOverrides: {}
        enabled: true
        name: edge-manager-preview
{{- end }}
{{ end }}