---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-manifests
  annotations:
    argocd.argoproj.io/sync-wave: "1"
{{- if .Values.nodes }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: update-agents-{{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.env }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
{{- end }}